/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as preworkTokenSol from "./PreworkToken.sol";
export type { preworkTokenSol };
export type { Greeter } from "./Greeter";
